export const STATUS = Object.freeze({
    "SUCCESSFUL_RESPONSE":200,
    "SUCCESSFUL_CREATED":201,
    "BAD_REQUEST":400,
    "UNAUTHORIZED":401,
    "NOT_FOUND":404,
    "UNPROCESSABLE_ENTITY":422,
    "INTERNAL_SERVER_ERROR":500
    });