export const TRANSACTION_AS = "Transaction as";
export const AMOUNT = "Amount";
export const LC_DETAILS = "LC Details";
export const IMPORTER_INFO = "Importer Info";
export const EXPORTER_INFO = "Exporter Info";
export const CONFIRMATION_CHARGES = "Confirmation Charges";
export const ATTACHMENTS = "Attachments";

export const CHOOSE_TYPE = "Choose Type";
export const APPLICANT_DETAILS = "Applicant Details";
export const LG_ISSUING_BANK = "LG issuing Bank";
export const TYPE_OF_LG = "Type of LG";
export const STANDARD_TEXT = "Standard Text";
export const LG_DETAILS = "LG Details";
export const BENEFICIARY = "Beneficiary";
export const PHYSICAL_LG = "Physical LG";
export const REMARKS = "Remarks";
export const PRICE_QUOTE = "Price Quote";
export const LG_PREFERRED_BANKS = "LG Preferred Banks";
