import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/context/ReactQueryProvider";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/context/AuthProvider";
const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
=======
    <html lang="en" suppressHydrationWarning>
>>>>>>> danish-dashboards
      <ReactQueryProvider>
        <AuthProvider>
          <body className={`${poppins.className}`}>{children}</body>
          <Toaster position="top-right" />
        </AuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
