export const tableData = [
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  {
    refNo: "100930",
    request: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "John Wick",
    lcApplicant: "BYCO",
    lcAmount: "USD 3,400,000.00",
    bids: 2,
  },
  // ...
];

export const columnHeaders = [
  "Ref no",
  "Request",
  "Expires",
  "Product Type",
  "LC Issuing Bank",
  "Beneficiary",
  "LC applicant",
  "LC Amount",
  "Bids",
];

export const bankTableData = [
  {
    dealsReceived: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "Anjum Mirza",
    lcApplicant: "Saif Arab",
    lcAmount: "USD 3,400,000.00",
    bids: "pending",
  },
  {
    dealsReceived: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "Anjum Mirza",
    lcApplicant: "Saif Arab",
    lcAmount: "USD 3,400,000.00",
    bids: "rejected",
  },
  {
    dealsReceived: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "Anjum Mirza",
    lcApplicant: "Saif Arab",
    lcAmount: "USD 3,400,000.00",
    bids: "add bid",
  },
  {
    dealsReceived: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "Anjum Mirza",
    lcApplicant: "Saif Arab",
    lcAmount: "USD 3,400,000.00",
    bids: "accepted",
  },
  {
    dealsReceived: "28 Feb 2023",
    expires: "28 Feb 2023",
    productType: "LC Confirmation",
    lcIssuingBank: "Habib Bank Ltd",
    beneficiary: "Anjum Mirza",
    lcApplicant: "Saif Arab",
    lcAmount: "USD 3,400,000.00",
    bids: "expired",
  },
];

export const bankColumnHeaders = [
  "Deal Received",
  "Expires",
  "Product Type",
  "LC Issuing Bank",
  "Beneficiary",
  "LC applicant",
  "LC Amount",
  "Bids",
];

export const myBidsData = [
  {
    dateSubmitted: "28 Feb 2023",
    country: "Pakistan",
    confirmationRate: "2.00%",
    discountingRate: "Not Applicable",
    discountMargin: "Not Applicable",
    minCharges: "USD 3,400,000.00",
    status: "pending",
  },
  {
    dateSubmitted: "28 Feb 2023",
    country: "Pakistan",
    confirmationRate: "2.00%",
    discountingRate: "Not Applicable",
    discountMargin: "Not Applicable",
    minCharges: "USD 3,400,000.00",
    status: "accepted",
  },
  {
    dateSubmitted: "28 Feb 2023",
    country: "Pakistan",
    confirmationRate: "2.00%",
    discountingRate: "Not Applicable",
    discountMargin: "Not Applicable",
    minCharges: "USD 3,400,000.00",
    status: "rejected",
  },
  {
    dateSubmitted: "28 Feb 2023",
    country: "Pakistan",
    confirmationRate: "2.00%",
    discountingRate: "Not Applicable",
    discountMargin: "Not Applicable",
    minCharges: "USD 3,400,000.00",
    status: "expired",
  },
];

export const myBidsColumnHeaders = [
  "Date Submitted",
  "Country of issuing bank",
  "Confirmation Rate",
  "Discounting Rate",
  "Discount Margin",
  "Minimum Charges",
  "Bid Status",
];
